SIDE_METRICS = [
    "chin_projection",
    "facial_convexity",
    "nasolabial_angle",
    "jaw_projection",
    "neck_chin_angle",
    "nose_projection",
    "lip_position",
]

SIDE_DEFS = {
    "chin_projection": {
        "rank": 1,
        "name": "Chin Projection",
        "unit": "x",
        "ideal_min": 0.035,
        "ideal_max": 0.085,
        "ideal_display": "0.035–0.085x",
        "scale_min": 0.00,
        "scale_max": 0.16,
        "scale_min_display": "0.00",
        "scale_max_display": "0.16",
        "about": "Horizontal chin projection relative to total profile height, using a stabilized soft-tissue chin estimate. This is a normalized 2D ratio, not a real-world millimeter measurement.",
        "weight": 1.0,
    },
    "facial_convexity": {
        "rank": 2,
        "name": "Facial Convexity",
        "unit": "°",
        "ideal_min": 160.0,
        "ideal_max": 172.0,
        "ideal_display": "160–172°",
        "scale_min": 148.0,
        "scale_max": 180.0,
        "scale_min_display": "148",
        "scale_max_display": "180",
        "about": "Angle describing profile convexity from glabella through subnasale to chin.",
        "weight": 1.2,
    },
    "nasolabial_angle": {
        "rank": 3,
        "name": "Nasolabial Angle",
        "unit": "°",
        "ideal_min": 88.0,
        "ideal_max": 112.0,
        "ideal_display": "88–112°",
        "scale_min": 75.0,
        "scale_max": 125.0,
        "scale_min_display": "75",
        "scale_max_display": "125",
        "about": "Angle between the stabilized nasal-base direction and the stabilized upper-lip direction.",
        "weight": 0.95,
    },
    "jaw_projection": {
        "rank": 4,
        "name": "Jaw Projection",
        "unit": "x",
        "ideal_min": 0.65,
        "ideal_max": 1.10,
        "ideal_display": "0.65–1.10x",
        "scale_min": 0.35,
        "scale_max": 1.60,
        "scale_min_display": "0.35",
        "scale_max_display": "1.60",
        "about": "Relative chin-to-nose projection balance in 2D profile space. This is a bounded projection-balance ratio, not a true skeletal jaw measurement.",
        "weight": 0.95,
    },
    "neck_chin_angle": {
        "rank": 5,
        "name": "Neck-Chin Angle",
        "unit": "°",
        "ideal_min": 98.0,
        "ideal_max": 122.0,
        "ideal_display": "98–122°",
        "scale_min": 85.0,
        "scale_max": 140.0,
        "scale_min_display": "85",
        "scale_max_display": "140",
        "about": "Angle formed by a stabilized neck point, chin, and subnasale. This metric remains more pose-sensitive than the other profile metrics.",
        "weight": 0.8,
    },
    "nose_projection": {
        "rank": 6,
        "name": "Nose Projection",
        "unit": "x",
        "ideal_min": 0.55,
        "ideal_max": 0.82,
        "ideal_display": "0.55–0.82x",
        "scale_min": 0.35,
        "scale_max": 1.00,
        "scale_min_display": "0.35",
        "scale_max_display": "1.00",
        "about": "Horizontal nasal projection proxy based on nose tip and subnasale.",
        "weight": 1.1,
    },
    "lip_position": {
        "rank": 7,
        "name": "Lip Position",
        "unit": "x",
        "ideal_min": -0.015,
        "ideal_max": 0.008,
        "ideal_display": "-0.015–0.008x",
        "scale_min": -0.050,
        "scale_max": 0.035,
        "scale_min_display": "-0.050",
        "scale_max_display": "0.035",
        "about": "Signed lower-lip position relative to the E-line, normalized by total profile height.",
        "weight": 0.95,
    },
}
